import { beforeEach, describe, expect, it, vi } from "vitest";
import { ALPHA_THRESHOLD, clearFloorplanImageCropCache, computeCropPlacement, floorplanImageCropCacheKey, floorplanImageCropDiagnostics, loadFloorplanImageCrop, scanAlphaContentBounds } from "./floorplan-image-crop";

const pixels = (width: number, height: number, entries: Array<[number, number, number]>) => { const data = new Uint8ClampedArray(width * height * 4); for (const [x, y, alpha] of entries) data[(y * width + x) * 4 + 3] = alpha; return data; };
const rectanglePixels = (width: number, height: number, left: number, top: number, right: number, bottom: number, alpha = 255) => { const entries: Array<[number, number, number]> = []; for (let y = top; y <= bottom; y += 1) for (let x = left; x <= right; x += 1) entries.push([x, y, alpha]); return pixels(width, height, entries); };

describe("floorPlan image transparent crop", () => {
  beforeEach(() => clearFloorplanImageCropCache());
  it("finds content after a fully transparent border", () => expect(scanAlphaContentBounds(rectanglePixels(8, 6, 2, 1, 6, 4), 8, 6)).toEqual({ x: 2, y: 1, width: 5, height: 4 }));
  it("removes a top-only transparent border", () => expect(scanAlphaContentBounds(rectanglePixels(5, 5, 0, 2, 4, 4), 5, 5)).toEqual({ x: 0, y: 2, width: 5, height: 3 }));
  it("removes left and right transparent borders", () => expect(scanAlphaContentBounds(rectanglePixels(7, 3, 2, 0, 4, 2), 7, 3)).toEqual({ x: 2, y: 0, width: 3, height: 3 }));
  it("removes transparent pixels on all four sides", () => expect(scanAlphaContentBounds(rectanglePixels(9, 9, 3, 2, 7, 6), 9, 9)).toEqual({ x: 3, y: 2, width: 5, height: 5 }));
  it("uses the centralized inclusive alpha threshold", () => expect(scanAlphaContentBounds(pixels(2, 1, [[0, 0, ALPHA_THRESHOLD], [1, 0, ALPHA_THRESHOLD - 1]]), 2, 1)).toEqual({ x: 0, y: 0, width: 1, height: 1 }));
  it("ignores all alpha values below the threshold", () => expect(scanAlphaContentBounds(pixels(2, 2, [[0, 0, 15], [1, 1, 1]]), 2, 2)).toBeNull());
  it("falls back to the whole image when alpha is empty", async () => { const entry = await loadFloorplanImageCrop("empty.png", async () => ({ naturalWidth: 4, naturalHeight: 3, data: new Uint8ClampedArray(48) })); expect(entry).toMatchObject({ cropX: 0, cropY: 0, cropWidth: 4, cropHeight: 3, isFallback: true, fallbackReason: "empty-alpha" }); });
  it("uses one uniform scale without deformation", () => { const placement = computeCropPlacement({ x: 0, y: 0, width: 400, height: 200 }, 2, 2)!; expect(placement.uniformScale).toBe(.005); expect(placement.drawWidth / placement.drawHeight).toBe(2); });
  it("computes draw dimensions from the same scale", () => expect(computeCropPlacement({ x: 0, y: 0, width: 300, height: 200 }, 1.2, .5)).toMatchObject({ drawWidth: .75, drawHeight: .5, uniformScale: .0025 }));
  it("centers cropped content in the physical footprint", () => expect(computeCropPlacement({ x: 0, y: 0, width: 100, height: 50 }, 2, 2)).toMatchObject({ offsetX: 0, offsetY: .5 }));
  it("fits wide content inside a tall footprint without stretching", () => { const placement = computeCropPlacement({ x: 0, y: 0, width: 400, height: 100 }, 1, 3)!; expect(placement).toMatchObject({ drawWidth: 1, drawHeight: .25 }); expect(placement.drawWidth / placement.drawHeight).toBe(4); });
  it("fits tall content inside a wide footprint without stretching", () => { const placement = computeCropPlacement({ x: 0, y: 0, width: 100, height: 400 }, 3, 1)!; expect(placement).toMatchObject({ drawWidth: .25, drawHeight: 1 }); expect(placement.drawWidth / placement.drawHeight).toBe(.25); });
  it("preserves an irregular content bbox aspect ratio", () => { const placement = computeCropPlacement({ x: 5, y: 7, width: 137, height: 83 }, 2, 1)!; expect(placement.drawWidth / placement.drawHeight).toBeCloseTo(137 / 83, 12); });
  it("reports aspect mismatch above five percent without blocking placement", async () => { const data = rectanglePixels(200, 100, 0, 0, 199, 99), node = { id: "item", type: "item", asset: { floorPlanUrl: "wide.png", dimensions: [1, 1, 1] }, scale: [1, 1, 1] }; await loadFloorplanImageCrop("wide.png", async () => ({ naturalWidth: 200, naturalHeight: 100, data })); expect(floorplanImageCropDiagnostics({ item: node } as any).some((item) => item.code === "floorplan_image_aspect_mismatch")).toBe(true); });
  it("uses unavailable fallback when pixel loading fails", async () => { const entry = await loadFloorplanImageCrop("cors.png", async () => { throw new Error("pixel-read-failed"); }); expect(entry).toMatchObject({ isFallback: true, fallbackReason: "pixel-read-failed" }); });
  it("deduplicates scans for the same URL and threshold cache key", async () => { const loader = vi.fn(async () => ({ naturalWidth: 1, naturalHeight: 1, data: pixels(1, 1, [[0, 0, 255]]) })); await Promise.all([loadFloorplanImageCrop("same.png", loader), loadFloorplanImageCrop("same.png", loader)]); expect(loader).toHaveBeenCalledTimes(1); expect(floorplanImageCropCacheKey("same.png")).toContain("alpha:16"); });
  it("does not mutate Item dimensions, center, rotation, or unrelated nodes", async () => { const nodes = { item: { id: "item", type: "item", position: [3, 0, 4], rotation: [0, 1, 0], asset: { floorPlanUrl: "stable.png", dimensions: [2, 1, 1] } }, wall: { id: "wall", type: "wall", start: [0, 0], end: [1, 0] } }, before = JSON.stringify(nodes); await loadFloorplanImageCrop("stable.png", async () => ({ naturalWidth: 1, naturalHeight: 1, data: pixels(1, 1, [[0, 0, 255]]) })); floorplanImageCropDiagnostics(nodes as any); expect(JSON.stringify(nodes)).toBe(before); });
});
