import { NodeData } from '../types';
import { resolveAncestorLevelId } from './transform';
type Point={x:number;z:number};
export type SpiralStair={center:Point;innerRadius:number;outerRadius:number;startAngle:number;endAngle:number;sweepAngle:number;treadLines:{start:Point;end:Point}[];footprint:Point[];footprintPath:string;upDirection:{from:Point;to:Point};centerColumn:Point|null;supportLines:{start:Point;end:Point}[];railingPaths:Point[][];landingGeometry:Point[]|null;sourceFields:string[];stepCount:number;railingMode:string};
const defaults={position:[0,0,0],rotation:0,stairType:'straight',fromLevelId:null,toLevelId:null,width:1,totalRise:2.5,stepCount:10,thickness:.25,fillToFloor:true,innerRadius:.9,sweepAngle:Math.PI/2,topLandingMode:'none',topLandingDepth:.9,showCenterColumn:true,showStepSupports:true,railingMode:'none',railingHeight:.92,children:[],slabOpeningMode:'none',openingOffset:0} as const;
const point=(c:Point,r:number,a:number):Point=>({x:c.x+r*Math.cos(a),z:c.z+r*Math.sin(a)});
export function resolveSpiralStair(node:NodeData){const sourceFields=Object.keys(defaults).filter(key=>!(key in node));return {...defaults,...node,sourceFields} as any;}
export function buildSpiralStairPlanGeometry(node:NodeData):SpiralStair|null{
 const s=resolveSpiralStair(node),p=Array.isArray(s.position)&&s.position.length>=3?s.position:null;
 if(!p||typeof s.width!=='number'||s.width<=0||typeof s.innerRadius!=='number'||s.innerRadius<=0||typeof s.sweepAngle!=='number'||!Number.isFinite(s.sweepAngle)||s.sweepAngle===0||!Number.isInteger(s.stepCount)||s.stepCount<1)return null;
 const center={x:p[0],z:p[2]},sweep=Math.abs(s.sweepAngle)>=Math.PI*2?Math.sign(s.sweepAngle)*(Math.PI*2-.001):s.sweepAngle,outerRadius=s.innerRadius+s.width,startAngle=-(s.rotation as number)-sweep/2,endAngle=startAngle+sweep;
 const landingSweep=s.topLandingMode==='integrated'?Math.sign(sweep)*Math.min(Math.PI*.75,Math.max(.3,s.topLandingDepth as number)/Math.max(s.innerRadius+s.width/2,.1)):0,visualEnd=endAngle+landingSweep,steps=s.stepCount as number,angles=Array.from({length:Math.max(24,Math.ceil(Math.abs(visualEnd-startAngle)/.12))+1},(_,i)=>startAngle+(visualEnd-startAngle)*i/(Math.max(24,Math.ceil(Math.abs(visualEnd-startAngle)/.12))));
 const footprint=[...angles.map(a=>point(center,outerRadius,a)),...angles.slice().reverse().map(a=>point(center,s.innerRadius,a))],treadLines=Array.from({length:steps+1},(_,i)=>{const a=startAngle+sweep*i/steps;return{start:point(center,s.innerRadius,a),end:point(center,outerRadius,a)}}),radius=s.innerRadius+s.width/2,arrowAngle=endAngle-sweep/steps*.8,upDirection={from:point(center,radius,arrowAngle-sweep/steps*.7),to:point(center,radius,arrowAngle+(Math.sign(sweep)>=0?Math.PI/2:-Math.PI/2)*.15)};
 const rail=(r:number)=>angles.map(a=>point(center,r,a)),railingPaths=[...(s.railingMode==='left'||s.railingMode==='both'?[rail(s.innerRadius)]:[]),...(s.railingMode==='right'||s.railingMode==='both'?[rail(outerRadius)]:[])];
 return {center,innerRadius:s.innerRadius,outerRadius,startAngle,endAngle,sweepAngle:sweep,treadLines,footprint,footprintPath:`M ${footprint.map(q=>`${q.x} ${q.z}`).join(' L ')} Z`,upDirection,centerColumn:s.showCenterColumn?center:null,supportLines:s.showStepSupports?treadLines:[],railingPaths,landingGeometry:s.topLandingMode==='integrated'?[point(center,s.innerRadius,endAngle),point(center,outerRadius,endAngle),point(center,outerRadius,visualEnd),point(center,s.innerRadius,visualEnd)]:null,sourceFields:s.sourceFields,stepCount:steps,railingMode:s.railingMode};
}
export const spiralStairCorners=(node:NodeData)=>buildSpiralStairPlanGeometry(node)?.footprint.map(p=>({x:p.x,z:p.z}))??[];
export const spiralStairLevelStatus=(node:NodeData,nodes:Record<string,NodeData>)=>({ancestor:resolveAncestorLevelId(node.id,nodes),missingReference:[node.fromLevelId,node.toLevelId].some(id=>id&&!nodes[id]),inconsistentReference:[node.fromLevelId,node.toLevelId].some(id=>id&&nodes[id]?.type!=='level')});
