import {Point2,Wall} from './types';
import {DEFAULT_WALL_THICKNESS} from './thickness';
const EPS=1e-6;
/** Pascal wall-curve.ts: normalizeWallCurveOffset, getWallCurveFrameAt, getWallSurfacePolygon. */
const start=(w:Wall):Point2=>({x:w.start[0],y:w.start[1]}),end=(w:Wall):Point2=>({x:w.end[0],y:w.end[1]});
const chord=(w:Wall)=>{const a=start(w),b=end(w),dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy);return{start:a,end:b,length:l,tangent:l<EPS?{x:1,y:0}:{x:dx/l,y:dy/l},normal:l<EPS?{x:0,y:1}:{x:-dy/l,y:dx/l},midpoint:{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}};
export function normalizedCurveOffset(w:Wall){const c=chord(w),max=c.length/2,raw=Math.max(-max,Math.min(max,w.curveOffset??0)),snap=Math.min(.03,Math.max(.005,c.length*.005));return Math.abs(raw)<=snap?0:raw}
export function isCurvedWall(w:Wall){return Math.abs(normalizedCurveOffset(w))>EPS}
export function getWallArcData(w:Wall){const c=chord(w),s=normalizedCurveOffset(w);if(Math.abs(s)<=EPS||c.length<EPS)return null;const radius=c.length*c.length/(8*Math.abs(s))+Math.abs(s)/2,direction=Math.sign(s)||1,centerOffset=radius-Math.abs(s),center={x:c.midpoint.x+c.normal.x*centerOffset*direction,y:c.midpoint.y+c.normal.y*centerOffset*direction},startAngle=Math.atan2(c.start.y-center.y,c.start.x-center.x),endAngle=Math.atan2(c.end.y-center.y,c.end.x-center.x);let delta=endAngle-startAngle;if(direction>0)while(delta<=0)delta+=Math.PI*2;else while(delta>=0)delta-=Math.PI*2;return{center,radius,startAngle,delta,direction}}
export function getWallCurveFrameAt(w:Wall,t:number){const c=chord(w),u=Math.max(0,Math.min(1,t));if(!isCurvedWall(w)||c.length<EPS)return{point:{x:c.start.x+(c.end.x-c.start.x)*u,y:c.start.y+(c.end.y-c.start.y)*u},tangent:c.tangent,normal:c.normal};const arc=getWallArcData(w)! ,angle=arc.startAngle+arc.delta*u,point={x:arc.center.x+Math.cos(angle)*arc.radius,y:arc.center.y+Math.sin(angle)*arc.radius},tangent=arc.direction>0?{x:-Math.sin(angle),y:Math.cos(angle)}:{x:Math.sin(angle),y:-Math.cos(angle)};return{point,tangent,normal:{x:-tangent.y,y:tangent.x}}}
export function getWallSurfacePolygon(w:Wall,segments=24,overrides?:{startLeft?:Point2;startRight?:Point2;endLeft?:Point2;endRight?:Point2}){const half=(w.thickness??DEFAULT_WALL_THICKNESS)/2,left:Point2[]=[],right:Point2[]=[];for(let i=0;i<=Math.max(1,segments);i++){const f=getWallCurveFrameAt(w,i/Math.max(1,segments));left.push({x:f.point.x+f.normal.x*half,y:f.point.y+f.normal.y*half});right.push({x:f.point.x-f.normal.x*half,y:f.point.y-f.normal.y*half})}left[0]=overrides?.startLeft??left[0];right[0]=overrides?.startRight??right[0];left[left.length-1]=overrides?.endLeft??left[left.length-1];right[right.length-1]=overrides?.endRight??right[right.length-1];return[...right,...left.reverse()]}
